---
# handlers file for setup-nginx
- name: reload systemd daemon
  systemd:
    daemon_reload: true
- name: restart nginx
  service:
    name: "nginx.service"
    state: restarted
    enabled: true
- name: restart logrotate
  service:
    name: "logrotate.service"
    state: restarted
- name: restart filebeat
  service:
    name: "filebeat.service"
    state: restarted
    enabled: true
