---
# tasks file for consul
- name: install utils
  apt:
    name:
      - curl
      - wget
      - net-tools
      - unzip
    update_cache: yes
    cache_valid_time: 3600
    state: present
    
- name: check if consultemplate exist
  stat:
    path: /usr/local/bin/consul
  register: consul_exist
- name: download consul
  unarchive:
    src: {{consul_download}}
    dest: /usr/local/bin
    remote_src: yes
  when: consul_exist.stat.exists == False
  
- name: create group consul
  group:
    name: consul
    system: yes
    state: present
- name: create user consul
  user:
    name: consul
    system: yes
    shell: /sbin/nologin
    state: present
    group: consul  
  
  
- name: create consul directory
  file:
    path: /var/lib/consul
    state: directory
    mode: 0755
    owner: consul
    group: consul

- name: create directory for consul configuration
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: consul
    group: consul
  with_items:
    - "{{ consul_home }}"
    - "{{ consul_home }}/bin"
    - "{{ consul_home }}/cert"
    - "{{ consul_data_dir }}"
    - "{{ consul_config_dir }}"

- name: create log directory if it does not exist
  file:
    state: directory
    path: {{ consul_log_file|dirname }}
    owner: consul
    group: consul
  when: not logdir.stat.exists


- name: touch the log file
  file:
    state: touch
    path: {{ consul_log_file }}
    owner: consul
    group: consul
  changed_when: false

    
- name: include for master
  include: master.yml
  when: consul_master is defined
  
- name: include for agent
  include: agent.yml
  when: consul_slave is defined
    
