- name: "get interfaces"
  shell:
    cmd: netplan get network.ethernets | grep -v ^" " | cut -d  ":" -f1
  register: interfaces

- name: configure DNS
  shell:
    cmd: netplan set ethernets."{{ item }}".nameservers.addresses="{{ nameservers }}"
  loop: "{{ interfaces.stdout_lines }}"

- name: netplan apply
  shell:
    cmd: netplan apply 
