---
#- include: time_configuration.yml
#- include: pg_hba_access.yml
- include: disable_swap.yml
- include: os_configuration.yml
- include: package_install.yml
  vars:
    cri: containerd
- include: cri_svc_config.yml
  vars:
    cri: containerd
- include: k8s_node_reset.yml
- include: k8s_node_join.yml
#- include: k8s_node_label.yml
