
- name: Copy tls files
  copy:
    src: tls/
    dest: "{{ vault_tls_path }}"
    owner: vault
    group: vault
    mode: 0600

- name: Copy ca ca-certificate
  copy:
    src: tls/hamidjahadi.ir.ca.crt
    dest: "{{ ca_certificates_local_dir }}"
    owner: root
    group: root
    mode: 0644
  notify: 
    - update ca-certificate
