- name: Installing Prerequest pkgs
  include_role:
    name: package-manager
  vars:
    pkgs_list: "{{ pre_vault_pkgs }}"
    action: 'install'

- name: Get Apt-Key Hashicorp
  environment: 
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  tags: 
    - apt-repo

- name: Add Hashicorp repository
  apt_repository:
    repo: deb  https://apt.releases.hashicorp.com "{{ ansible_distribution_release }}" main
    state: present
    filename: Docker
  tags: 
    - apt-repo

- name: Install Vault
  apt:
    name: vault
    update_cache: yes
  when:
    - ansible_distribution|string == 'Ubuntu'
    - ansible_distribution_version  in ['18.04','20.04','22.04','9','10','11'] 